### ISSUE TITLE
Document Wave configurations and Variables 

### ISSUE THREAD

**Issue by munishchouhan** [seqeralabs/wave#355]
We need to document and explain and provide examples for all config and variables required for wave deployment 
```[tasklist]
### Tasks
- [x] List all the config variables
- [x] Describe all the config variables
- [x] Provide sample values for those variables
```

**Comment by bebosudo** [comment]
Note that I was working on a Helm chart for wave here: https://github.com/seqeralabs/helm-charts/pull/1 (effort issue here: https://github.com/seqeralabs/helm-charts/issues/6)

I was initially thinking of storing the wave manifests as part of the tower helm chart (like we already do for groundswell), but I'm now thinking of creating a separate helm chart for wave, and integrating the two later on (like we do for the redis and mysql charts from bitnami).
