### ISSUE TITLE
Documentation of Wave Deployments

### ISSUE THREAD

**Issue by munishchouhan** [seqeralabs/wave#363]
This issue will track the progress of various documents required for wave deployments.

```[tasklist]
### Tasks
- [ ] Add introduction
- [ ] Add pre-requisites
- [ ] Add configuration documentation
- [ ] Add installation guide
```

**Comment by munishchouhan** [comment]
PR for configuration documentation  https://github.com/seqeralabs/wave/pull/360

**Comment by marcodelapierre** [comment]
As discussed with Munish, a good starting reference can be the Installation docs for the Seqera cloud: https://docs.seqera.io/platform/23.3.0/enterprise

**Comment by jason-seqera** [comment]
From https://github.com/seqeralabs/wave/pull/360, how many of these are going to be user facing variables? I don't think we expose every possible variable for Platform, for example. Thanks!

**Comment by munishchouhan** [comment]
@jason-seqera Yes, I think there is no need to expose micronaut variables to the user
I will make the necessary changes

**Comment by munishchouhan** [comment]
Installation guide will be added in https://github.com/seqeralabs/platform-installer

**Comment by jason-seqera** [comment]
@munishchouhan, the customer facing product documentation or for internal use?

**Comment by pditommaso** [comment]
Customer installation docs

**Comment by munishchouhan** [comment]
For now the guide for self host wave is present here
https://github.com/seqeralabs/wave-k8s-deployment/blob/master/README.md

Once it get integrated with platform-installer, we will add documentation there too

**Comment by gavinelder** [comment]
There is now customer facing installation documentation within the repository , a helm chart and terraform examples.
